### PR TITLE
Feature/sqpit 598 arm64 simulator support arm64 simulator support

### PR DESCRIPTION
**Pull request by billypchan**
dummy PR for testing auto comment action

### CODE REVIEW

**Review by billchan2021 — APPROVED** [review]

**Review by billchan2021 — COMMENTED** [review]
blah

**Review by billchan2021 — APPROVED** [review]

**Review by billchan2021 — COMMENTED** [review]
f

**Review by billypchan — COMMENTED** [review]
b

**Review by billchan2021 — APPROVED** [review]

**Review by billchan2021 — COMMENTED** [review]
ff

**Review by billchan2021 — APPROVED** [review]

**Review by billchan2021 — COMMENTED** [review]
f

**Review by billchan2021 — APPROVED** [review]

**Review by billchan2021 — COMMENTED** [review]
f

**Review by billchan2021 — APPROVED** [review]

**Review by billchan2021 — COMMENTED** [review]
f

**Review by billchan2021 — APPROVED** [review]

**Review by billchan2021 — COMMENTED** [review]
d

**Review by billchan2021 — APPROVED** [review]

**Review by billchan2021 — COMMENTED** [review]
f

**Review by billchan2021 — APPROVED** [review]

**Review by billchan2021 — COMMENTED** [review]
f

**Review by billchan2021 — APPROVED** [review]

**Review by billchan2021 — COMMENTED** [review]
f

**Review by billchan2021 — APPROVED** [review]

**Comment by billypchan** [comment]
b

**Review by billypchan — COMMENTED** [review]
f

**Comment by billypchan** [comment]
f

**Comment by billypchan** [comment]
release minor

**Comment by billypchan** [comment]
D

**Comment by billypchan** [comment]
release minor

**Comment by billypchan** [comment]
release minor

**Comment by billypchan** [comment]
release minor

**Comment by billypchan** [comment]
release minor

**Comment by billypchan** [comment]
release

**Comment by billypchan** [comment]
b

**Comment by billypchan** [comment]
b

**Comment by billypchan** [comment]
a

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Comment by billypchan** [comment]
release major

**Pull request merged**
